// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7jlX_7umiuqrJZhFmyMzpOWtxOdusCKM',
    appId: '1:833225352309:web:7b9fd30f0205268972c43c',
    messagingSenderId: '833225352309',
    projectId: 'titweng-cattle-recognition',
    authDomain: 'titweng-cattle-recognition.firebaseapp.com',
    storageBucket: 'titweng-cattle-recognition.firebasestorage.app',
    measurementId: 'G-7EXEB12DLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2TofIt6mjF_XMHTx1EIB9QHdoE-sGiqM',
    appId: '1:833225352309:android:92920114ff3bd50772c43c',
    messagingSenderId: '833225352309',
    projectId: 'titweng-cattle-recognition',
    storageBucket: 'titweng-cattle-recognition.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBJqL9HiM99uaa-e0zIDDTj5XLIoAkAEA',
    appId: '1:833225352309:ios:3935c2130735a22972c43c',
    messagingSenderId: '833225352309',
    projectId: 'titweng-cattle-recognition',
    storageBucket: 'titweng-cattle-recognition.firebasestorage.app',
    iosBundleId: 'titweng-cattle-recognition',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBJqL9HiM99uaa-e0zIDDTj5XLIoAkAEA',
    appId: '1:833225352309:ios:3935c2130735a22972c43c',
    messagingSenderId: '833225352309',
    projectId: 'titweng-cattle-recognition',
    storageBucket: 'titweng-cattle-recognition.firebasestorage.app',
    iosBundleId: 'titweng-cattle-recognition',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7jlX_7umiuqrJZhFmyMzpOWtxOdusCKM',
    appId: '1:833225352309:web:7b9fd30f0205268972c43c',
    messagingSenderId: '833225352309',
    projectId: 'titweng-cattle-recognition',
    authDomain: 'titweng-cattle-recognition.firebaseapp.com',
    storageBucket: 'titweng-cattle-recognition.firebasestorage.app',
    measurementId: 'G-7EXEB12DLC',
  );
}